services:
  app:
    build: .
    volumes:
      - .:/app # Mount the entire project directory
      - ./data:/app/data:rw # Explicitly mount data directory with read-write
      - ./output:/app/output:rw # Explicitly mount output directory with read-write
    ports:
      - "8050:8050" # For the Dash app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
    command: >
      sh -c "python src/main.py --data data/raw_data.csv --output output &&
             python src/visualization/app.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 10s
      retries: 3
