services:
  - type: web
    name: treehut-trend-analysis
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
      mkdir -p data output
    startCommand: gunicorn src.visualization.app:server --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATA_PATH
        value: /opt/render/project/src/data/engagements.csv
      - key: OUTPUT_PATH
        value: /opt/render/project/src/output
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
